from django.urls import path
from menu.views import (
    index,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    IngredientListView,
    SpecializationListView,
    CookListView,
    DishListView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    CookDetailView,
    DishTypeDetailView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    IngredientDetailView,
    IngredientCreateView,
    IngredientUpdateView,
    IngredientDeleteView,
    SpecializationDeleteView,
    SpecializationUpdateView,
    SpecializationCreateView,
    SpecializationDetailView,
)


urlpatterns = [
    path(
        "",
        index,
        name="index"
    ),

    path(
        "dish-types/",
        DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish-types/<int:pk>/",
        DishTypeDetailView.as_view(),
        name="dish-type-detail"
    ),

    path(
        "dish-types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),

    path(
        "ingredients/",
        IngredientListView.as_view(),
        name="ingredient-list"
         ),
    path(
        "ingredients/<int:pk>/",
        IngredientDetailView.as_view(),
        name="ingredient-detail"
    ),

    path(
        "ingredients/create/",
        IngredientCreateView.as_view(),
        name="ingredient-create",
    ),
    path(
        "ingredients/<int:pk>/update/",
        IngredientUpdateView.as_view(),
        name="ingredient-update",
    ),
    path(
        "ingredients/<int:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="ingredient-delete",
    ),

    path(
        "specializations/",
        SpecializationListView.as_view(),
        name="specialization-list"
    ),
    path(
        "specializations/<int:pk>/",
        SpecializationDetailView.as_view(),
        name="specialization-detail"
    ),

    path(
        "specializations/create/",
        SpecializationCreateView.as_view(),
        name="specialization-create",
    ),
    path(
        "specializations/<int:pk>/update/",
        SpecializationUpdateView.as_view(),
        name="specialization-update",
    ),
    path(
        "specializations/<int:pk>/delete/",
        SpecializationDeleteView.as_view(),
        name="specialization-delete",
    ),

    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "cooks/create/",
        CookCreateView.as_view(),
        name="cook-create",
    ),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),

    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),

    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create",
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update",
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete",
    ),
]

app_name = "menu"
